---
id: 2
name: TipStream V2 Mainnet Deployment
network: mainnet
stacks-node: "https://api.hiro.so"
bitcoin-node: "http://blockstack:blockstacksystem@bitcoin.blockstack.com:8332"
plan:
  batches:
    - id: 0
      transactions:
        - contract-publish:
            contract-name: tipstream-traits
            expected-sender: SP1W6XQZ6XVYGTVW32SJW2ZG48ZJBW9BATRD19N60
            cost: 100000
            path: contracts/tipstream-traits.clar
            anchor-block-only: true
            clarity-version: 2
        - contract-publish:
            contract-name: tipstream
            expected-sender: SP1W6XQZ6XVYGTVW32SJW2ZG48ZJBW9BATRD19N60
            cost: 500000
            path: contracts/tipstream-v2.clar
            anchor-block-only: true
            clarity-version: 2
      epoch: "3.0"
