---
id: 0
name: TipStream V3 mainnet deployment
network: mainnet
stacks-node: "https://api.hiro.so"
bitcoin-node: "http://blockstack:blockstacksystem@bitcoin.blockstack.com:8332"
plan:
  batches:
    - id: 0
      transactions:
        - contract-publish:
            contract-name: tipstream-traits
            expected-sender: SP31PKQVQZVZCK3FM3NH67CGD6G1FMR17VQVS2W5T
            cost: 220000
            path: contracts/tipstream-traits.clar
            anchor-block-only: true
            clarity-version: 2
        - contract-publish:
            contract-name: tipstream-v3
            expected-sender: SP31PKQVQZVZCK3FM3NH67CGD6G1FMR17VQVS2W5T
            cost: 7100000
            path: contracts/tipstream-v3.clar
            anchor-block-only: true
            clarity-version: 2
      epoch: "3.0"
